version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
#      working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=vishva
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - web
  website:
    container_name: php72
    build:
      context: ./
    ports:
      - 8001:80
    volumes: 
      - "./src:/var/www/html/"
    depends_on:
      - mysql
    networks:
      - web
networks:
   web:
